# Generated by Django 5.0 on 2023-12-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
