# Generated by Django 5.0 on 2023-12-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_usertagcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTadCount',
        ),
    ]
