# Generated by Django 5.0 on 2023-12-11 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.IntegerField(choices=[(0, 'CUSTOM'), (1, 'LEGS'), (2, 'ARMS'), (3, 'CORE'), (4, 'CARDIO')], default=0)),
                ('completed', models.BooleanField(default=False)),
                ('exercises', models.ManyToManyField(related_name='workout', to='exercise.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
    ]
